### ISSUE TITLE
webpack - uglifyJs

### ISSUE THREAD

**Issue by c1rus** [flauc/angular2-notifications#112]
ERROR in js/main.js from UglifyJs
SyntaxError: Unexpected token: name (NotificationsService) [js/main.js:25756,6]

i tried to run it without uglify plugin and i see this:
```
...
"use strict";
"use strict";
const core_1 = __webpack_require__(0);
const Subject_1 = __webpack_require__(56);
const icons_1 = __webpack_require__(636);
class NotificationsService {
...
```

Shouldnt the js files published to npm be in es5?

**Comment by GitHubish** [comment]
i have the same problem on IE11 et Firefox.

**Comment by maxbrodin** [comment]
It seems that typescript files compiled to `es2015` target and uglify expects `es5`

**Comment by otiteca** [comment]
Any updates or solution on that issue?

**Comment by notprathap** [comment]
I have forked the repo and updated target to es5 and types to "core-js" - this fixed the issue. If it works for everyone, then perhaps one of us can raise a pull request.

**Comment by flauc** [comment]
Hi @notprathap,

Have you tried it in both AoT and JiT?

Thank you for the hard work 👍

**Comment by notprathap** [comment]
Works on AoT. Didn't test it on JiT, but the tsconfig already had reference to core-js types, so I'd expect it to work. I can test it over the weekend, if no one else gets around to it

**Comment by flauc** [comment]
That would be great, I'm completely swamped at the moment.

**Comment by mharris7190** [comment]
Is this updated then? I'm getting the same problem with uglify plugin

**Comment by reprise-dev** [comment]
I'm having the same issue, but this time it's in gulp:

[00:19:01] Error: SyntaxError: Unexpected token: name (SimpleNotificationsModule) (line: 16997, col: 18, pos: 922156)

**Comment by notprathap** [comment]
Sorry guys, will attend to this tomorrow (Monday)

**Comment by notprathap** [comment]
@flauc think my pull request should fix this. Have tested it with both AOT and JIT. Would be great to see if it solves the issue for everyone

**Comment by reprise-dev** [comment]
Hi, 

Sorry to be a pain, (this is coming from someone new to Angular 2), I've tried looking around your github project site on how I would take your pull request and use it inside our project.

I used the npm package site to download it before but it hasn't been updated for 4 weeks so  I was wondering how I can take what you've done and use it today?

Thanks heaps!

**Comment by notprathap** [comment]
hey, no worries. 
My changes have now been integrated into master - so you can use from this repo itself. The only difference is that you may have to run a npm install after you download the repo locally through npm.  This is how you do it: 

"angular2-notifications": "git+https://git@github.com/flauc/angular2-notifications.git",

on your package.json.

This will download code directly from github inside your node_modules folder. Then you cd into that folder, and run npm install, and you will have the latest version.  You can then run your build from your root directory, and the uglify plugin should work as expected.

This is workaround until @flauc updates the dist at npm registry, to which I don't have access to.  Once he's done that, we can switch back our package.json with the original entry pointing npm registry.

Good luck!

**Comment by flauc** [comment]
Hey @notprathap, man you're quick at responding, thanks again for the great job you did with fixing this 👍 

@reprise-dev I've just pushed the new version with the updated code from @notprathap to npm so doing `npm install angular2-notifications` should get you 0.4.48 now.

**Comment by reprise-dev** [comment]
Hi @notprathap and @flauc 

Thanks so much for your help, I just used the updated npm package and it's working perfectly!

Great component guys, very useful for our project!

**Comment by thanhtran621992** [comment]
Hi guys,
I got the same problem with uglifyJs when I build the app. I tried to upgrade notifications component to 0.4.48 and the error has gone.
But I got the new error when I run my app after upgraded component to 0.4.48:

![screenshot from 2016-12-26 15 15 41](https://cloud.githubusercontent.com/assets/14305328/21478496/7ae0fb94-cb7e-11e6-806c-ccd7c053644c.png)

**Comment by notprathap** [comment]
Hey,
It appears unrelated to this package. May be try upgrading Angular core?

**Comment by thanhtran621992** [comment]
Hi @notprathap , 
Thanks for your response, My app now back to normal :) .

**Comment by nabokov-ef** [comment]
Hi @thanhtran621992 and @notprathap!
I have the error "Uncaught TypeError: e.map is not a function"
![emapisnotafunction](https://cloud.githubusercontent.com/assets/3168823/22608465/07d05a50-ea6e-11e6-92e4-79aeb991f74b.png)
I got this error after upgrading angular2-notifications from 0.4.47 to 0.4.48. The version 0.4.51 does not work too. Any ideas?
I have all angular modules updated:
`    "@angular/common": "2.4.6",
    "@angular/compiler": "2.4.6",
    "@angular/core": "2.4.6",
    "@angular/forms": "2.4.6",
    "@angular/http": "2.4.6",
    "@angular/platform-browser": "2.4.6",
    "@angular/platform-browser-dynamic": "2.4.6",
    "@angular/platform-server": "2.4.6",
    "@angular/router": "3.4.6",
`
[This is my package.json](http://pastebin.com/J6spMeKq).

**Comment by ziglee** [comment]
C:\project-angular>ng build --aot -prod
Hash: 8ddcb81f9b9d32957f60
Time: 10443ms
chunk    {0} polyfills.18173234f9641113b9fe.bundle.js (polyfills) 158 kB {4} [initial] [rendered]
chunk    {1} main.7f8a8e3b0a3381ae8447.bundle.js (main) 252 kB {3} [initial] [rendered]
chunk    {2} styles.d41d8cd98f00b204e980.bundle.css (styles) 69 bytes {4} [initial] [rendered]
chunk    {3} vendor.3cdc7b78c109abe1bb75.bundle.js (vendor) 1.56 MB [initial] [rendered]
chunk    {4} inline.8e4c7c9c5ad58e9775a4.bundle.js (inline) 0 bytes [entry] [rendered]

ERROR in vendor.3cdc7b78c109abe1bb75.bundle.js from UglifyJs
Unexpected token: name (SimpleNotificationsComponent) [vendor.3cdc7b78c109abe1bb75.bundle.js:27591,4]

`{
  "name": "project-angular",
  "version": "1.0.0",
  "license": "MIT",
  "engines": {
    "node": "6.10.0",
    "npm": "3.10.10"
  },
  "scripts": {
    "ng": "ng",
    "start": "node server.js",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "postinstall": "ng build --aot -prod"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.0.1",
    "@angular/cli": "1.0.0",
    "@angular/common": "^4.0.1",
    "@angular/compiler": "^4.0.0",
    "@angular/compiler-cli": "^4.0.0",
    "@angular/core": "^4.0.1",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "angular2-notifications": "^0.5.3",
    "core-js": "^2.4.1",
    "express": "^4.15.2",
    "ng2-notify": "^1.4.0",
    "rxjs": "^5.1.0",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@types/jasmine": "2.5.38",
    "@types/node": "~6.0.60",
    "codelyzer": "~2.0.0",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "protractor": "~5.1.0",
    "ts-node": "~2.0.0",
    "tslint": "~4.5.0",
    "typescript": "~2.2.0"
  }
}
`

**Comment by prostoandrei** [comment]
@ziglee had same problem. Just update your packages.
