### ISSUE TITLE
Angular 4 Release

### ISSUE THREAD

**Issue by amihailes** [flauc/angular2-notifications#169]
Hi,

Is it possible to have an Angular 4 Release built based version?

Thanks in advance,

Adrian

**Comment by flauc** [comment]
Hi @amihailes,

Didn't have a chance to test yet. It would be very helpful if someone did have a chance though.

**Comment by Baidaly** [comment]
@amihailes I just tried this with the latest Angular 4 and it worked fine

**Comment by ClemensSchneider** [comment]
I have the same issues as described in https://github.com/flauc/angular2-notifications/issues/168
The toast-notification never disappears (was working with Angular 2). Could be related to the animation-module that was relocated in Angular 4?

**Comment by bomberblue07** [comment]
I have the same issue as above after upgrading to 4.0 today

**Comment by Baidaly** [comment]
@ClemensSchneider Did you import Browser Animation module? Also, did you install @angular/animation package?

**Comment by bomberblue07** [comment]
@Baidaly doing that worked for me, thanks!

**Comment by ClemensSchneider** [comment]
Thanks, that worked!

**Comment by siovene** [comment]
The library works fine for me after importing the Browser Animations module, however I get warnings about peer dependencies when installing it. Perhaps the package.json could be updated?

**Comment by vladotesanovic** [comment]
```
npm install @angular/animations --save
```

in app.module.ts
```
@NgModule({
  imports: [
    ...
    BrowserAnimationsModule
    ...
  ],
  providers: [],
  declarations: [],
  bootstrap: [
    AppComponent
  ]
})
export class AppModule {}
```

**Comment by amihailes** [comment]
Maybe rename the library in angular-notifications.......
It seems google wants to delete the angular2 reference....

**Comment by Scipionh** [comment]
Where are we on this ?

**Comment by edyrkaj** [comment]
I got this error on vendors.
Uncaught SyntaxError: Unexpected token export
export * from './src/push-notifications.module';

**Comment by jm-sqribl** [comment]
I'm using angular 4 and CLI. After following the install instructions I get "Cannot find name 'NotificationsService'." The directory is in my node_modules but it fails on compilation. 

It seems like others are able to get it to work with Angular 4 but I'm having fits. 

Thanks

**Comment by Prashant-Kan** [comment]
I am using angular 4 and Cli. After executing the steps given. When I run the page where I have implemented the "<simple-notifications [options]="options"></simple-notifications>", It throws console error saying "simple-notifications" is an unknown element and hence further processing of the page also fails. Resulting in 5,6 console errors.

Does anyone face this same issue earlier. Do anyone knows the solution for the same?

Thanks

**Comment by aethel** [comment]
@jm-sqribl maybe try importing the service into your component by adding:

import { NotificationsService } from 'angular2-notifications';

**Comment by flauc** [comment]
The library should now support ng5 nicely.
